### ISSUE TITLE
pcb alternative/ brake

### ISSUE THREAD

**Issue by wf2020** [TSDZ2-ESP32/TSDZ2-ESP32-Wiki#1]
Hello,

I came across your projects and it seems really nicely made. Already made a request at PCBways, Result: 79 USD for two pieces, taking about one month.

Two questions:

(1) I'm considering using an ESP32-PICO-Kit V4 instead with additional level shifters and suitable power supply, Just flashed your bin files to it. Would there be an issue because there is a 40MHz crystal on board?

(2) I would like to keep brake sensors but can't find configuration options in your app.

Thank you.

**Comment by mspider65** [comment]
About every ESP32 dev Kit will works fine. No issues at all with the Frequency.

Brake signal is used by the controller firmware if present. No option parameters needed.

**Comment by wf2020** [comment]
Thanks a lot. I think I will give it a trial.

Did you consider integrating communication with smart bms for true capacity display?

**Comment by mspider65** [comment]
No, because I don't have it and I don't think there is a standard protocol for smart bms

**Comment by wf2020** [comment]
All usual bms I know are LLT/JBD Xiaoxiang Smart BMS using this serial protocol:

https://www.lithiumbatterypcb.com/Protocol%20English%20Version.rar
