### ISSUE TITLE
emmebrusa controller firmware compatibility?

### ISSUE THREAD

**Issue by washichi** [TSDZ2-ESP32/TSDZ2-ESP32-Wiki#3]
I'm currently using the emmebrusa firmware for my TSDZ2, I know it contains a lot of improvements from this controller firmware.
Does the emmebrusa firmware support the ESP32 Controller? Or are those projects existing next to each other?

**Comment by dzid26** [comment]
Probably not.
Emmebrusa and Mspider (ESP32) firmwares diverged quite a bit. I think emmbrusa was picking some changes from Cashino and Mspider. But he was doing it manually and git history doesn't show exactly what comes from where and what emmebrusa did himself.

**Comment by washichi** [comment]
You are right, they are not compatible. I was a bit confused because the wiki of Emmebrusa is referenced in this project.
But they are separate projects. (where some features are implemented in both)
